
package pl.edu.agh.soa.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentServiceInterface", targetNamespace = "http://soap.soa.agh.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentServiceInterface {


    /**
     * 
     * @param albumNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteStudent", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.DeleteStudent")
    @ResponseWrapper(localName = "deleteStudentResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.DeleteStudentResponse")
    public String deleteStudent(
        @WebParam(name = "albumNumber", targetNamespace = "")
        int albumNumber);

    /**
     * 
     * @param albumNumber
     * @return
     *     returns pl.edu.agh.soa.soap.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentResponse")
    public Student getStudent(
        @WebParam(name = "albumNumber", targetNamespace = "")
        int albumNumber);

    /**
     * 
     * @param courseName
     * @return
     *     returns java.util.List<pl.edu.agh.soa.soap.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentsByCourse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentsByCourse")
    @ResponseWrapper(localName = "getStudentsByCourseResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentsByCourseResponse")
    public List<Student> getStudentsByCourse(
        @WebParam(name = "courseName", targetNamespace = "")
        String courseName);

    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIcon", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetIcon")
    @ResponseWrapper(localName = "getIconResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetIconResponse")
    public byte[] getIcon();

    /**
     * 
     * @param faculty
     * @return
     *     returns java.util.List<pl.edu.agh.soa.soap.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentsByFaculty", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentsByFaculty")
    @ResponseWrapper(localName = "getStudentsByFacultyResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetStudentsByFacultyResponse")
    public List<Student> getStudentsByFaculty(
        @WebParam(name = "faculty", targetNamespace = "")
        String faculty);

    /**
     * 
     * @param profesorName
     * @param courseName
     * @param ects
     * @param hours
     * @param profesorSurname
     * @param albumNumber
     * @return
     *     returns pl.edu.agh.soa.soap.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCourseToStudent", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddCourseToStudent")
    @ResponseWrapper(localName = "addCourseToStudentResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddCourseToStudentResponse")
    public Student addCourseToStudent(
        @WebParam(name = "albumNumber", targetNamespace = "")
        int albumNumber,
        @WebParam(name = "courseName", targetNamespace = "")
        String courseName,
        @WebParam(name = "profesorName", targetNamespace = "")
        String profesorName,
        @WebParam(name = "profesorSurname", targetNamespace = "")
        String profesorSurname,
        @WebParam(name = "ects", targetNamespace = "")
        int ects,
        @WebParam(name = "hours", targetNamespace = "")
        int hours);

    /**
     * 
     * @param field
     * @param surname
     * @param name
     * @param albumNumber
     * @return
     *     returns pl.edu.agh.soa.soap.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.AddStudentResponse")
    public Student addStudent(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "surname", targetNamespace = "")
        String surname,
        @WebParam(name = "field", targetNamespace = "")
        String field,
        @WebParam(name = "albumNumber", targetNamespace = "")
        int albumNumber);

    /**
     * 
     * @return
     *     returns java.util.List<pl.edu.agh.soa.soap.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://soap.soa.agh.edu.pl/", className = "pl.edu.agh.soa.soap.GetAllStudentsResponse")
    public List<Student> getAllStudents();

}
